# Generated by Django 5.0 on 2024-01-09 18:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeC', models.CharField(choices=[('C001', 'C001'), ('C002', 'C002'), ('C003', 'C003')], max_length=10, unique=True)),
                ('designation_centre', models.CharField(choices=[('Centre1', 'centre1'), ('Centre2', 'centre2'), ('Centre3', 'centre3')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeCl', models.CharField(max_length=10, unique=True)),
                ('nomCl', models.CharField(max_length=50)),
                ('prenomCl', models.CharField(max_length=50)),
                ('adresseCl', models.CharField(max_length=100)),
                ('telephoneCl', models.CharField(max_length=20)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeF', models.CharField(max_length=10, unique=True)),
                ('nomF', models.CharField(max_length=50)),
                ('prenomF', models.CharField(max_length=50)),
                ('adresseF', models.CharField(max_length=100)),
                ('telephoneF', models.CharField(max_length=20)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeM', models.CharField(max_length=10, unique=True)),
                ('designation_matiere', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('quantiteStockMat', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeP', models.CharField(max_length=10, unique=True)),
                ('designation_produit', models.CharField(max_length=50)),
                ('prix_unitaire_Ven', models.DecimalField(decimal_places=2, default='0.0', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('quantiteStockPod', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeEmp', models.CharField(max_length=50, unique=True)),
                ('nomEmp', models.CharField(max_length=50)),
                ('prenomEmp', models.CharField(max_length=50)),
                ('adresseEmp', models.CharField(max_length=100)),
                ('telephoneEmp', models.CharField(max_length=20)),
                ('salaire_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EmployeCentre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Massrouf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demende_at', models.DateTimeField(auto_now=True)),
                ('montant_dem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
            options={
                'unique_together': {('employe', 'demende_at')},
            },
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyed_at', models.DateTimeField(auto_now=True)),
                ('prix_unitaire_HT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantitHT', models.IntegerField()),
                ('montantTotalHT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fournisseur')),
                ('matiere_achete', models.ForeignKey(default='M001', on_delete=django.db.models.deletion.CASCADE, to='app.matierepremiere')),
            ],
            options={
                'unique_together': {('fournisseur', 'matiere_achete', 'buyed_at')},
            },
        ),
        migrations.CreateModel(
            name='PaymentAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_at', models.DateTimeField(default=datetime.datetime.now)),
                ('montant_reglement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fournisseur')),
            ],
            options={
                'unique_together': {('fournisseur', 'pay_at')},
            },
        ),
        migrations.CreateModel(
            name='PaymentVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_at', models.DateTimeField(default=datetime.datetime.now)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
            options={
                'unique_together': {('client', 'pay_at')},
            },
        ),
        migrations.CreateModel(
            name='TransfertMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_at', models.DateTimeField(auto_now=True)),
                ('quantitTran', models.IntegerField()),
                ('cout_transfere', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('matiere_transfere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
            options={
                'unique_together': {('centre', 'matiere_transfere', 'transfer_at')},
            },
        ),
        migrations.CreateModel(
            name='TransfertProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_at', models.DateTimeField(auto_now=True)),
                ('quantitTran', models.IntegerField()),
                ('cout_transfere', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('produit_transfere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
            options={
                'unique_together': {('centre', 'produit_transfere', 'transfer_at')},
            },
        ),
        migrations.CreateModel(
            name='VenteM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salled_at', models.DateTimeField(auto_now=True)),
                ('prix_unitaire_Ven', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantitVen', models.IntegerField()),
                ('montantTotalVen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('matiere_vendus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.matierepremiere')),
            ],
            options={
                'unique_together': {('client', 'matiere_vendus', 'salled_at')},
            },
        ),
        migrations.CreateModel(
            name='VenteP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salled_at', models.DateTimeField(auto_now=True)),
                ('prix_unitaire_Ven', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantitVen', models.IntegerField()),
                ('lieu_ventes', models.CharField(choices=[('Centre1', 'centre1'), ('Centre2', 'centre2'), ('Centre3', 'centre3')], max_length=20)),
                ('montantTotalVen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('produit_vendus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
            options={
                'unique_together': {('client', 'produit_vendus', 'salled_at')},
            },
        ),
    ]
