# Generated by Django 5.0 on 2024-01-11 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transfertprod',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='transfertprod',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='transfertprod',
            name='produit_transfere',
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_at', models.DateTimeField(auto_now=True)),
                ('quantitTran', models.IntegerField()),
                ('cout_transfere', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('produit_transfere', models.ForeignKey(default='M001', on_delete=django.db.models.deletion.CASCADE, to='app.matierepremiere')),
            ],
            options={
                'unique_together': {('centre', 'produit_transfere', 'transfer_at')},
            },
        ),
        migrations.DeleteModel(
            name='TransfertMat',
        ),
        migrations.DeleteModel(
            name='TransfertProd',
        ),
    ]
