# Generated by Django 5.0 on 2024-01-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_transfertprod_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
