# Generated by Django 5.0 on 2024-01-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.centre'),
        ),
    ]
