# Generated by Django 5.0 on 2024-01-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_transfert_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.matierepremiere')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
            options={
                'unique_together': {('produit', 'matiere')},
            },
        ),
    ]
