# Generated by Django 5.0 on 2024-01-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_centre_active_client_active_employe_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='prix_unitaire_Ven',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=15),
        ),
    ]
