# Generated by Django 5.0 on 2024-01-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_matierepremiere_prix_unitaire_ven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='buyed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='massrouf',
            name='demende_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='matierepremiere',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymentachat',
            name='pay_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymentvente',
            name='pay_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='transfer_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ventem',
            name='salled_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ventep',
            name='salled_at',
            field=models.DateTimeField(),
        ),
    ]
