# Generated by Django 5.0 on 2024-01-22 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_achat_buyed_at_alter_massrouf_demende_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='quantitDispo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='massrouf',
            name='demende_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='massrouf',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employe'),
        ),
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abcence', models.DateTimeField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employe')),
            ],
            options={
                'unique_together': {('employe', 'date_abcence')},
            },
        ),
    ]
