# Generated by Django 5.0 on 2024-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_achat_quantitdispo_alter_massrouf_demende_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='codeC',
            field=models.CharField(choices=[('c1', 'c1'), ('c2', 'c2'), ('c3', 'c3')], max_length=10, unique=True),
        ),
    ]
