# Generated by Django 5.0.1 on 2024-01-23 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_centre_codec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='matiere_achete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.matierepremiere'),
        ),
    ]
