# Generated by Django 5.0.1 on 2024-01-23 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_achat_matiere_achete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ventep',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ventep',
            name='lieu_ventes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.centre'),
        ),
        migrations.AlterUniqueTogether(
            name='ventep',
            unique_together={('client', 'produit_vendus', 'salled_at', 'lieu_ventes')},
        ),
    ]
