# Generated by Django 5.0.1 on 2024-01-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_ventep_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matierepremiere',
            name='created_at',
        ),
    ]
