# Generated by Django 5.0.1 on 2024-01-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_matierepremiere_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='created_at',
        ),
    ]
