# Generated by Django 5.0.7 on 2024-07-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_produit_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='salaire_jour',
            new_name='salaire_base',
        ),
    ]
