# Generated by Django 5.0.7 on 2024-07-25 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_salaire_jour_employe_salaire_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='exit_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateTimeField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employe')),
            ],
            options={
                'unique_together': {('employe', 'date_sortie')},
            },
        ),
    ]
