# Generated by Django 5.0.7 on 2024-07-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_exit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payed_at',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payement', models.DateTimeField(unique=True)),
            ],
        ),
    ]
