# Generated by Django 5.0.7 on 2024-07-31 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_payed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_at', models.DateTimeField()),
                ('quantitCom', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('produit_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produit')),
            ],
            options={
                'unique_together': {('client', 'produit_commande', 'command_at')},
            },
        ),
    ]
