# Generated by Django 5.0.7 on 2024-08-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payed_at',
            name='date_payement',
            field=models.DateField(unique=True),
        ),
    ]
