# Generated by Django 5.0.7 on 2024-08-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_payed_at_date_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='sexe',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
