# Generated by Django 5.0.7 on 2024-08-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_employe_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='sexe',
        ),
        migrations.AlterField(
            model_name='absent',
            name='date_abcence',
            field=models.DateField(),
        ),
    ]
