# Generated by Django 5.0.7 on 2024-08-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_employe_sexe_alter_absent_date_abcence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='date_abcence',
            field=models.DateTimeField(),
        ),
    ]
