# Generated by Django 5.0.7 on 2024-08-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_absent_date_abcence'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='date_achat',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='prix_achat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='quantitCom',
            field=models.IntegerField(null=True),
        ),
    ]
