# Generated by Django 5.0.7 on 2024-08-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_command_date_achat_command_prix_achat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='command',
            name='date_achat',
            field=models.DateTimeField(),
        ),
    ]
