# Generated by Django 5.0.7 on 2024-08-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_command_command_at_alter_command_date_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventep',
            name='khesara',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ventep',
            name='mosa3ada',
            field=models.IntegerField(null=True),
        ),
    ]
