# Generated by Django 5.0.7 on 2024-08-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_ventep_montanttotalvenneutre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='codeC',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='centre',
            name='designation_centre',
            field=models.CharField(max_length=50),
        ),
    ]
