# Generated by Django 5.0.7 on 2024-08-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_centre_codec_alter_centre_designation_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
