# Generated by Django 5.1 on 2024-08-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_transfert_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matierepremiere',
            name='prix_unitaire_Ven',
        ),
    ]
