# Generated by Django 5.1 on 2024-08-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_matierepremiere_prix_unitaire_ven'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='adresseF',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='prenomF',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='telephoneF',
        ),
    ]
