from django.urls import path
from . import views

urlpatterns = [
    path('paymentachat/', views.payerAchat, name="payerht"),
    path('paymentvente/', views.payerVente, name="payervt"),
    path('histpymtachat/', views.liste_paiemens_achat, name="histpymtachat"),
    path('histpymtvente/', views.liste_paiements_vente, name="histpymtvente"),
    path('histpymtachat/modifierpayment/<int:payment_id>', views.modifier_paymentht, name="modifierPyamentHT"),
    path('histpymtachat/supprimerpayment/<int:payment_id>', views.supprimer_paymentht, name="supprimerPaymentHT"),
    path('histpymtvente/modifierpayment/<int:payment_id>', views.modifier_paymentvt, name="modifierPyamentVT"),
    path('histpymtvente/supprimerpayment/<int:payment_id>', views.supprimer_paymentvt, name="supprimerPaymentVT"),
    path('achat/', views.fiche_journal_achats, name="achat"),
    path('achat/add_achat/', views.sava_achat, name='ajouterAchat'),
    path('achat/modifierachat/<int:achat_id>/', views.modifier_achat, name='modifierAchat'),
    path('achat/supprimerachat/<int:achat_id>/', views.supprimer_achat, name='supprimerAchat'),
    path('vente/', views.fiche_journal_ventes_interport, name="venteI"),
    path('vente/add_vents_matiere/', views.sava_ventes_matiere, name='ajouterVenteMatiere'),
    path('ventecentre1/<str:center_id>/', views.fiche_journal_ventes_centre1),
    path('ventecentre2/', views.fiche_journal_ventes_centre2, name="venteC2"),
    path('ventecentre3/', views.fiche_journal_ventes_centre3, name="venteC3"),
    path('vente/modifiervente/<int:vente_id>/', views.modifier_vente_mat, name='modifierVenteMat'),
    path('vente/supprimervente/<int:vente_id>/', views.supprimer_vente_mat, name='supprimerVenteMat'),
    path('ventecentre/add_vents/', views.sava_ventes, name='ajouterVenteCentre'),
    path('ventecentre/modifiervente/<int:vente_id>/', views.modifier_vente_prod, name='modifierVenteProd'),
    path('ventecentre/supprimervente/<int:vente_id>/', views.supprimer_vente_prod, name='supprimerVenteProd'),
    path('etatstock/', views.fiche_journal_Stock, name="stock"),
    path('etatstock/add_matiere/', views.save_matiere, name='ajouterMatiere'),
    path('etatstock/modifiermatiere/<int:matiere_id>/', views.modifier_matiere, name='modifierMat'),
    path('etatstock/supprimermatiere/<int:matiere_id>/', views.supprimer_matiere, name='supprimerMat'),
    path('systemePointage', views.systemePointage),
    path('Salaire', views.CalculerSalaire),
    path('transfert/', views.fiche_journal_transferts, name="Transfert"),
    path('transfert/add_tranfer/', views.save_transfer, name='ajouterTransfert'),
    path('transfert/modifiertransfert/<int:transfert_id>/', views.modifier_transfert, name="modifierTransfert"),
    path('transfert/supprimertransfert/<int:transfert_id>/', views.supprimer_transfert, name="supprimerTransfert"),
    path('transfertrecucentre1/<str:center_id>/', views.fiche_journal_transferts_recu_centre1),
    path('transfertrecucentre2/', views.fiche_journal_transferts_recu_centre2, name="TransfertRecuC2"),
    path('transfertrecucentre3/', views.fiche_journal_transferts_recu_centre3, name="TransfertRecuC3"),
    path('register/', views.register_page, name="register"),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
    path('', views.login_page, name="login"),
    path('logout/', views.logout_page, name="logout"),
    path('index/', views.indexView, name="home"),
    path('produits/', views.fiche_jornal_produits, name='listProduits'),
    path('produits/add_produits/', views.save_produit, name='insererProduit'),
    path('produits/modifier/<int:produit_id>/', views.modifier_produit, name='modifierProduit'),
    path('produits/supprimer/<int:produit_id>/', views.supprimer_produit, name='supprimerProduit'),
    path('fournisseurs/', views.fiche_jornal_fournisseurs, name='listFournisseurs'),
    path('fourniseurs/add_fournisseur/', views.save_fournisseur, name='ajouterFournisseur'),
    path('fourniseurs/modifier/<int:fourniseur_id>/', views.modifier_fournisseur, name='modifierFourniseur'),
    path('fourniseurs/supprimer/<int:fourniseur_id>/', views.supprimer_fournisseur, name='supprimerFourniseur'),
    path('clients/', views.fiche_jornal_clients, name='listClients'),
    path('clients/add_client/', views.save_client, name='ajouterClient'),
    path('clients/modifier/<int:client_id>/', views.modifier_client, name='modifierClient'),
    path('clients/supprimer/<int:client_id>/', views.supprimer_client, name='supprimerClient'),
    path('centres/', views.fiche_jornal_centres, name='listCentres'),
    path('centres/add_centre/', views.save_centre, name='ajouterCentre'),
    path('centres/modifier/<int:centre_id>/', views.modifier_centre, name='modifierCentre'),
    path('centres/supprimer/<int:centre_id>/', views.supprimer_centre, name='supprimerCentre'),
    path('employes/', views.fiche_jornal_employes, name='listEmployes'),
    path('employes/add_employe/', views.save_employe, name='ajouterEmploye'),
    path('employes/modifier/<int:employe_id>/', views.modifier_employe, name='modifierEmploye'),
    path('employes/supprimer/<int:employe_id>/', views.supprimer_employe, name='supprimerEmploye'),
    path('notification', views.notification, name='afficherNotifications'),
   path('analyse', views.analyse, name='analyseGenerale'),
    path('Centre', views.analyseCentres, name='analyseCentre'),
path('Centre1/<str:center_id>/', views.centre1),
    path('Centre2', views.centre2, name='analyseCentre2'),
    path('Centre3', views.centre3, name='analyseCentre3'),
    path('analyse_centre1/<str:center_id>/', views.analyse_centre1),
   path('analyse_centre2', views.analyse_centre2, name='detailAnalyseCentre2'),
   path('analyse_centre3', views.analyse_centre3, name='detailAnalyseCentre3'),
   path('systemePointage/<int:employe_id>/',views.systemePointage,name='systemePointage'),
   path('Salaire',views.CalculerSalaire,name='Salaire'),
   path('notification',views.notification,name='notification'),
   path('adminnotifier',views.envoyer_email,name='adminnotif'),
   path('command/', views.fiche_jornal_command, name='listCommand'),
   path('modifier_command/<int:commande_id>/', views.modifier_command, name='modifierCommand'),
    path('supprimer_command/<int:commande_id>/', views.supprimer_command, name='supprimerCommand'),
    path('ajouter_command/', views.inserer_commande, name='ajouterCommande'),
    path('includes/side-bar.html/', views.sidebar_view),

]

