from .achat_views import *
from .client_views import *
from .fournisseur_views import *
from .produit_views import *
from .analyse_views import *
from .auth_views import *
from .centre_views import *
from .employe_views import *
from .mailDEV_views import *
from .notification_views import *
from .pointage_views import *
from .reglement_views import *
from .stock_views import *
from .transfert_views import *
from .vente_views import *
